# Generated by Django 4.0.1 on 2022-01-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
